name: Coveralls


on:
  push:
    branches: [ "coverage" ]
  pull_request:
    branches: [ "coverage" ]


jobs:
  build:


    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - name: Cloning repo
      uses: actions/checkout@v4
    - name: Use Node.js 21.x
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
    - name: Installing dependencies root
      run: npm ci
    - name: Installing dependencies server
      working-directory: ./server
      run: npm ci
    - name: Generating coverage information
      working-directory: ./server
      run: npm run coverage
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.2.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token: ${{ secrets.COVERALLS_REPO_TOKEN }}